app/urls.py
# app/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('get_user_orders/', views.get_user_orders, name='get_user_orders'),
    path('dish/', views.dishes, name='dish'),
    path('operator/', views.operator, name='operator'),
    path('menu_page', views.menu_page, name='menu_page'),
    path('createmenu/', views.createmenu, name='createmenu'),
    path('replace_week_number/', views.replace_week_number, name='replace_week_number'),
    path('menu_view', views.menu_view, name='menu_view'),
    path('add_to_cart/', views.add_to_cart, name='add_to_cart'),
    path('submit_order/', views.submit_order, name='submit_order'),
    path('dish_del', views.dish_del, name='dish_del'),
    path('load-dishes/', views.load_dishes, name='load_dishes'),
    path('upd_menu', views.upd_menu, name='upd_menu'),
    path('', views.index, name='index'),
    path('orders/', views.orders, name='orders'),
    path('account/', views.account, name='account'),
    path('upd_user', views.upd_user, name='upd_user'),
    path('upd_pswd', views.upd_pswd, name='upd_pswd'),
    path('sign_up/', views.sign_up, name='sign_up'),
    path('check_tabel_number', views.check_tabel_number, name='check_tabel_number'),
    path('update_order_status/<int:order_number>/', views.update_order_status, name='update_order_status'),
    path('delete_order/<int:order_number>/', views.delete_order, name='delete_order'),
    path('dish/update/', views.dish_update, name='dish_update'),
    path('delete_menu_item/<int:menu_item_id>/', views.delete_menu_item, name='delete_menu_item'),
    path('get_dishes_by_category/<int:category_id>/', views.get_dishes_by_category, name='get_dishes_by_category'),
    path('update_menu_item/<int:id>/', views.update_menu_item, name='update_menu_item'),
    path('archive_order/', views.archive_order, name='archive_order'),
    path('send_receipt/<int:order_number>/', views.send_receipt, name='send_receipt'),
    path('password_reset/', auth_views.PasswordResetView.as_view(template_name='registration/password_reset.html', 
                                                                email_template_name='registration/password_rst_email.html' ), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='registration/password_rst_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='registration/password_rst_confirm.html'), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_rst_complete.html'), name='password_reset_complete'),
    path('service/', views.service, name='service'),
    path('order_archive', views.order_archive, name='order_archive'),
    path('run-archive-expired-orders/', views.run_archive_expired_orders, name='run_archive_expired_orders'),
    path('run-send-archived-orders-email/', views.run_send_archived_orders_email, name='run_send_archived_orders_email'),
    path('run-send-orders-email/', views.run_send_orders_email, name='run_send_orders_email'),
    path('run-tabel-number/', views.run_tabel_number, name='run-tabel-number'),
    path('initiate-payment/<int:user_id>/', views.initiate_payment, name='initiate_payment'),
    path('callback/', views.callback, name='callback'),
    path('balance/', views.balance, name='balance'),
    path('initiate-refund/<int:user_id>/', views.initiate_refund, name='initiate_refund'),
]

myproject/urls.py
from django.contrib import admin
from django.urls import path, include  # new
from django.views.generic.base import TemplateView

urlpatterns = [
    path("366/", admin.site.urls),
    path("users/", include("django.contrib.auth.urls")),
    path("", include("app.urls")),  # new
]

app/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from datetime import datetime
from django.core.exceptions import ValidationError
from decimal import Decimal

class City(models.Model):
    name = models.CharField('Linn', max_length=50, blank=False, unique=True)

    def __str__(self):
        return self.name

class User(AbstractUser):
    tabel_number = models.CharField('Töötaja number', max_length=10, blank=False, unique=True)
    blocked = models.BooleanField('Blokeeritud', blank=False, default=False)
    city = models.ForeignKey('City', on_delete=models.PROTECT, related_name='users', default=1)
    balance = models.DecimalField('Saldo', max_digits=5, decimal_places=2, default=0.00)

class Transaction(models.Model):
    TRANSACTION_TYPES = [
        ('deposit', 'Sissemakse'),
        ('withdrawal', 'Väljamakse'),
        ('refund', 'Tagastus'),
    ]

    user = models.ForeignKey('User', on_delete=models.CASCADE, related_name='transactions')
    amount = models.DecimalField('Summa', max_digits=10, decimal_places=2)
    transaction_type = models.CharField('Tehingu tüüp', max_length=10, choices=TRANSACTION_TYPES)
    created_at = models.DateTimeField('Tehingu kuupäev', auto_now_add=True)
    description = models.TextField('Kirjeldus', blank=True)
    payment_reference = models.CharField('Makse identifikaator', max_length=255, blank=True, null=True)

    def __str__(self):
        return f"{self.user.username} - {self.get_transaction_type_display()} - {self.amount} EUR"

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        # Uuendame kasutaja saldot tehingu salvestamisel
        if self.transaction_type == 'deposit':
            self.user.balance += Decimal(str(self.amount))  # Teisendame stringi Decimaliks
        elif self.transaction_type == 'withdrawal':
            self.user.balance -= Decimal(str(self.amount))  # Teisendame stringi Decimaliks
        elif self.transaction_type == 'refund':
            self.user.balance -= Decimal(str(self.amount))  # Teisendame stringi Decimaliks
        self.user.save()

class table_number(models.Model):
    tabel_number = models.CharField('Tabelinumber', max_length=10, blank=False, unique=True)
    def __str__(self):
        return self.tabel_number

class category(models.Model):
    category_name = models.CharField('Kategooria', max_length=25, blank=False)
    def __str__(self):
        return self.category_name

class weekday(models.Model):
    weekday_name = models.CharField('Päev', max_length=15, blank=False)
    def __str__(self):
        return self.weekday_name

class dish(models.Model):
    dish_name = models.CharField('Roog', max_length=50, blank=False)
    dish_price = models.DecimalField('Hind', max_digits=10, decimal_places=2, blank=False)
    category = models.ForeignKey('category', on_delete=models.CASCADE)
    def __str__(self):
        return f"{self.category}, {self.dish_name} ({self.dish_price} EUR)"

class week(models.Model):
    number = models.IntegerField('Nädal', blank=False)
    def __str__(self):
        return str(self.number)

class menu(models.Model):
    week_number = models.ForeignKey('week', on_delete=models.PROTECT)
    weekday_id = models.ForeignKey('weekday', on_delete=models.PROTECT)
    dish_id = models.ForeignKey('dish', on_delete=models.PROTECT)
    created_at = models.DateTimeField(auto_now_add=True)  # Lisame loomiskuupäeva välja

    def __str__(self):
        return f"(Nädal {self.week_number}, {self.weekday_id}) {self.dish_id}"

class order(models.Model):
    order_number = models.BigIntegerField('Tellimuse number')
    user_id = models.ForeignKey('User', on_delete=models.PROTECT)
    menu_id = models.ForeignKey('Menu', on_delete=models.PROTECT)
    quantity = models.IntegerField('Kogus', blank=False)
    city = models.ForeignKey('City', on_delete=models.PROTECT, related_name='orders')

    def __str__(self):
        return f"{self.order_number}, {self.user_id}, {self.menu_id}, {self.quantity}, {self.city}"

    def save(self, *args, **kwargs):
        if not self.order_number:
            # Genereerime tellimuse numbri
            current_year = datetime.now().year
            week_number = int(self.menu_id.week_number.number)
            day_number = int(self.menu_id.weekday_id.id)
            tabel_number = int(self.user_id.tabel_number)
            
            # Kui praegune nädal on 52 ja tellimus on nädalale 1, siis suurendame aastat ühe võrra
            if datetime.now().isocalendar()[1] == 52 and week_number >= 1:
                current_year += 1
            elif datetime.now().isocalendar()[1] == 1 and datetime.now().month == 12:
                current_year += 1
            else:
                current_year = current_year

            # Moodustame tellimuse numbri
            self.order_number = int(f"{current_year}{week_number:02d}{day_number:02d}{tabel_number:05d}")
        
        # Kontrollime, kas kasutajal on tellimuse maksmiseks piisavalt vahendeid
        total_amount = self.quantity * self.menu_id.dish_id.dish_price
        if self.user_id.balance >= total_amount:
            # Loome tehingu vahendite lahutamiseks
            Transaction.objects.create(
                user=self.user_id,
                amount=total_amount,
                transaction_type='withdrawal',
                description=f"Makse saldolt tellimuse {self.order_number} eest"
            )
        super().save(*args, **kwargs)
    
class ArchivedOrder(models.Model):
    STATUS_CHOICES = [
        (1, 'Väljastatud'),
        (3, 'Aegunud'),
    ]

    order_number = models.BigIntegerField('Tellimuse number', unique=True)
    user_tabel_number = models.CharField('Kasutaja tabelinumber', max_length=10)
    user_username = models.CharField('Kasutajanimi', max_length=150)
    dishes = models.TextField('Roogad', blank=True)
    city_name = models.CharField('Linn', max_length=50)
    total_amount = models.DecimalField('Tellimuse summa', max_digits=10, decimal_places=2, blank=False)
    archived_at = models.DateTimeField(auto_now_add=True)  # Tellimuse arhiveerimise kuupäev
    status = models.PositiveIntegerField(choices=STATUS_CHOICES, default=3)

    def __str__(self):
        return f"{self.order_number}, {self.user_username}, {self.dishes}, {self.city_name}, {self.total_amount}, Staatus: {self.get_status_display()}"

    def clean(self):
        if self.status not in [1, 2, 3]:
            raise ValidationError("Vigane staatusväärtus.")

    @staticmethod
    def archive_order(order_number):
        # Kasutame otse order mudelit
        order_items = order.objects.filter(order_number=order_number)
        if not order_items.exists():
            return

        user = order_items.first().user_id
        city = order_items.first().city
        total_amount = sum(order_item.quantity * order_item.menu_id.dish_id.dish_price for order_item in order_items)

        dish_list = []
        for order_item in order_items:
            dish = order_item.menu_id.dish_id
            dish_list.append(f"{dish.dish_name} ({order_item.quantity} tk.) ({order_item.menu_id.dish_id.dish_price} EUR)")

        dishes_str = ', '.join(dish_list)

        ArchivedOrder = ArchivedOrder.objects.create(
            order_number=order_number,
            user_tabel_number=user.tabel_number,
            user_username=user.username,
            dishes=dishes_str,
            city_name=city.name,
            total_amount=total_amount,
            status=3  # Vaikimisi staatus on 'Paid'
        )

        order_items.delete()

app/templates/app/base.html
<!--app/templates/app/base.html-->
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>foodbook</title>
    <link rel="icon" type="image/x-icon" href="{% static 'img/favicon.ico' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flaticon-test-uicons@1.7.2/css/all/all.min.css">

    {% block style %}
    {% endblock %}
  </head>
  <body>
    <div class="container">
      <header class="d-flex flex-wrap justify-content-center py-3 mb-4 border-bottom">
        <a href="/" class="d-flex align-items-center text-decoration-none">
          <span class="fs-4">foodbook</span>
        </a>
      </header>
    </div>
    <div class="container col-xl-10 col-xxl-8 px-4">
      <div class="main d-flex row align-items-start g-lg-5 py-5">
    {% block content %} 
    {% endblock %}
    {% block form %} 
    {% endblock %}
      </div>
    </div>
    <div class="modal fade" id="GDPR_modal" tabindex="-1" aria-labelledby="GDPR_modalLabel" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="GDPR_modalLabel">Kasutajatingimused</h5>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
          <div class="modal-body">
            <p>
              Kasutajatingimused lõunasöökide tellimise süsteemi veebirakendusele tootmisettevõttes Aquaphor International OÜ
            </p>
            <ol>
              <li>
                <strong>Üldsätted</strong>
                <ol>
                  <li>
                    Käesolevad kasutajatingimused (edaspidi "Tingimused") reguleerivad suhteid Aquaphor International OÜ (registreerimisnumber: [sisesta registreerimisnumber], aadress: [sisesta aadress]) ja töötaja (edaspidi "Kasutaja") vahel, kes kasutab lõunasöökide tellimise süsteemi veebirakendust (edaspidi "Rakendus").
                  </li>
                  <li>
                    Rakenduse kasutamine tähendab kasutaja täielikku ja tingimusteta nõusolekut käesolevate tingimustega.
                  </li>
                  <li>
                    Aquaphor International OÜ jätab endale õiguse muuta käesolevaid tingimusi. Kõik muudatused jõustuvad nende avaldamise hetkest rakenduses.
                  </li>
                </ol>
              </li>
              <li>
                <strong>Rakenduse eesmärk</strong>
                <ol>
                  <li>
                    Rakendus on loodud Aquaphor International OÜ töötajate lõunasöökide tellimise protsessi lihtsustamiseks.
                  </li>
                  <li>
                    Kasutaja kohustub kasutama rakendust ainult isiklikel eesmärkidel, mis on seotud lõunasöökide tellimise teenuse kasutamisega.
                  </li>
                </ol>
              </li>
              <li>
                <strong>Poolte õigused ja kohustused</strong>
                <ol>
                  <li>
                    Aquaphor International OÜ kohustub:
                    <ul>
                      <li>Tagama kasutajale ligipääsu rakendusele</li>
                      <li>Tagada rakenduse korrektne töö</li>
                      <li>Esitada info saadaolevate roogade ja nende hinna kohta</li>
                    </ul>
                  </li>
                  <li>
                    Kasutaja kohustub:
                    <ul>
                      <li>Kasutama rakendust vastavalt selle otstarbele</li>
                      <li>Tasuma rakenduse kaudu tehtud tellimused täielikult</li>
                      <li>Mitte kasutada rakendust käesolevate tingimustega mitteühilduvatel eesmärkidel</li>
                    </ul>
                  </li>
                </ol>
              </li>
              <li>
                <strong>Tellimuste tasumine</strong>
                <ol>
                  <li>
                    Kasutaja nõustub, et kõik rakenduse kaudu tehtud tellimused tuleb tasuda täielikult.
                  </li>
                  <li>
                    Tellimuste maksumus määratakse rakenduses esitatud info põhjal ja võib sisaldada Eesti seadusandlusega ettenähtud makse ja tasusid.
                  </li>
                  <li>
                    Tellimuste tasumine võib toimuda rakendusse integreeritud maksesüsteemi kaudu või muul Aquaphor International OÜ poolt määratud viisil.
                  </li>
                </ol>
              </li>
              <li>
                <strong>Vastutus</strong>
                <ol>
                  <li>
                    Aquaphor International OÜ ei vastuta kasutajale tekitatud kahju eest, mis on tingitud rakenduse valest kasutamisest, välja arvatud juhul kui kahju on põhjustatud Aquaphor International OÜ tahtlikust tegevusest või suurest hooletusest.
                  </li>
                  <li>
                    Kasutaja vastutab täielikult rakenduse kaudu tehtud tellimuste eest tasumise ning rakenduse valekasutamise tagajärgede eest.
                  </li>
                </ol>
              </li>
              <li>
                <strong>Andmete konfidentsiaalsus ja kaitse</strong>
                <ol>
                  <li>
                    Aquaphor International OÜ kohustub järgima Eesti isikuandmete kaitse seadusi ja tagama kasutaja poolt esitatud info konfidentsiaalsuse.
                  </li>
                  <li>
                    Kasutaja nõustub, et Aquaphor International OÜ võib koguda ja töödelda isikuandmeid, mis on vajalikud rakenduse kasutamiseks, sealhulgas kuid mitte piiratud nime, kontaktandmete ja tellimuste andmetega.
                  </li>
                </ol>
              </li>
              <li>
                <strong>Lepingu lõppemine</strong>
                <ol>
                  <li>
                    Aquaphor International OÜ jätab endale õiguse ühepoolselt lõpetada leping, kui kasutaja rikub käesolevaid tingimusi.
                  </li>
                  <li>
                    Kasutaja võib lõpetada rakenduse kasutamise igal ajal, kuid kohustub tasuma kõik lepingu lõppemise hetkeks tehtud tellimused.
                  </li>
                </ol>
              </li>
              <li>
                <strong>Vaidluste lahendamine</strong>
                <ol>
                  <li>
                    Kõik lepingu täitmisest tulenevad vaidlused ja lahkarvamused tuleb lahendada poolte vaheliste läbirääkimiste teel.
                  </li>
                  <li>
                    Kui vaidlust ei õnnestu lahendada läbirääkimiste teel, allub see lahendamisele Eesti seaduste kohaselt.
                  </li>
                </ol>
              </li>
              <li>
                <strong>Lõppsätted</strong>
                <ol>
                  <li>
                    Käesolev leping reguleeritakse ja tõlgendatakse vastavalt Eesti seadustele.
                  </li>
                  <li>
                    Kui mõni käesoleva lepingu sätteid tunnistatakse kehtetuks või jõustumisvõimetuks, ei mõjuta see ülejäänud sätete kehtivust.
                  </li>
                  <li>
                    Käesolev leping jõustub kasutaja nõusoleku andmisel selle tingimustega ja kehtib kuni lepingu lõppemiseni vastavalt punktile 7.1.
                  </li>
                </ol>
              </li>
            </ol>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-primary" data-bs-dismiss="modal">Tingimused on arusaadavad</button>
          </div>
        </div>
      </div>
    </div>
    <script src="{% static 'js/bootstrap.js' %}"></script>
    <script src="{% static 'js/jquery-3.7.1.min.js' %}"></script>
    <script>
      $("#id_tabel_number").keyup(function(e){
        e.preventDefault();
        var tabel_number = $(this).val();
        console.log(tabel_number.length);
        if(tabel_number.length === 4){
          $.ajax({
            url: '{% url 'check_tabel_number' %}',
            type: 'POST',
            data: {tabel_number: tabel_number},

            success: function(response){
              console.log(response);
              if(response.exists){
                $(".tb_error").remove();
                $("<span class='tb_error' style='padding: 5px;color: red;'>" + response.message + "</span>").insertAfter("#id_tabel_number");
              } else {
                $(".tb_error").remove();
                $("#id_username").attr("disabled", false);
                $("#id_first_name").attr("disabled", false);
                $("#id_last_name").attr("disabled", false);
                $("#id_email").attr("disabled", false);
                $("#id_password1").attr("disabled", false);
                $("#id_password2").attr("disabled", false);
                const checkbox = document.getElementById('GDPR');
                const submitButton = document.getElementById('reg');
               
                checkbox.addEventListener('change', function() {
                    if (this.checked) {
                        $("#reg").attr("disabled", false);
                    } else {
                        $("#reg").attr("disabled", true);
                    }
                });
                $("<span class='tb_error' style='padding: 5px;color: green;'>" + response.message + "</span>").insertAfter("#id_tabel_number");
              }
            },
            error: function(){
              console.log("failed");
            }
          });
        } else {
          $("#id_username").attr("disabled", true);
          $("#id_first_name").attr("disabled", true);
          $("#id_last_name").attr("disabled", true);
          $("#id_email").attr("disabled", true);
          $("#id_password1").attr("disabled", true);
          $("#id_password2").attr("disabled", true);
          $("#reg").attr("disabled", true);
          $(".tb_error").remove();
        }
      });
    </script>
    {% block custom_js %} 
    {% endblock %}
  </body>
</html>